### ISSUE TITLE
Increase disk space for cuda build

### ISSUE THREAD

**Issue by pearu** [conda-forge/omniscidb-feedstock#5]
Issue:

The cuda build of omniscidb fails with `No space left on device` when setting up conda build environment.

Diagnostics:

Azure has about 13 GB of free disk space (out of 84 GB) which is sufficient for cpu build but not for cuda build. 

Workaround:

Before executing the build script, one needs to free up some space by inserting the following script block before the `Run docker build` block in [azure-pipelines-linux.yml](https://github.com/conda-forge/omniscidb-feedstock/blob/master/.azure-pipelines/azure-pipelines-linux.yml):
```
  - script: |
        rm -rf /opt/ghc
        df -h
    displayName: Manage disk space (rm /opt/ghc)
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
```
Note that the azure-pipelines-linux.yml file is generated by conda-smithy so that one must re-insert the above code block after each re-render.
